<?php session_start(); ?>
<style>
    .category-view{
        display:none;
    }
    .block-content filter-content{
        display:none;
    }
    .sidebar{
        display:none;
    }
</style>

<?php
$cnt = 0;
$custom_helper = $this->helper(CWH\Category\Helper\Data::class);

if($custom_helper->getConfig() == 1){

    $category = $this->getLayout()->createBlock('\CWH\Category\Block\Category')->getCurrentCategory();

    if(!empty($category->getData('h1_title'))) {
        echo "<div class='custom-h1-title'>".$category->getData('h1_title')."</div>";
    }

    $subcats = $category->getChildrenCategories();

    if($subcats->getData() && $category->getData('category_collection')==1)
    {
?>

        <ul style="padding: 0px;float: left;width: 100%">
            <?php
                foreach ($subcats as $subcat) {
                    $cnt++;
                    if ($subcat->getIsActive()) {
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                        $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
                        $subcaturl = $subcat->getUrl();

                        $_imgHtml = '';
                        if ($_imgUrl = $_category->getImageUrl()) {

                            $_imgHtml = '<img style="width: 100%;" src="' . $_imgUrl . '" />';
                            $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');

                            /* @escapeNotVerified */
                            echo '<li style="list-style-type: none;width:24%;margin-right:1%;float:left"><a href="' . $subcaturl . '" class="block-promo" title="' . $subcat->getName() . '">' . $_imgHtml . '</a>'.$subcat->getName().'</li>';
                        }
                    }
                } 
            ?>
        </ul>

<?php 
    }else{
        include ($block->getTemplateFile('Magento_Catalog::product/list.phtml'));
    }
}else{
    include ($block->getTemplateFile('Magento_Catalog::product/list.phtml'));
}
?>

<script>
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready( function() {
            var cnt = <?php echo json_decode($cnt); ?>;
            if(cnt==0){
                $('.sidebar').show();
            }else{
                $('.column').css(
                    "width" ,"100%"
                );
            }
        });
    });
</script>